### ISSUE TITLE
Attempting to join gives error

### ISSUE THREAD

**Issue by gl1tchy1203** [ViaVersion/ViaProxy#222] opened 2024-05-26 19:50 UTC
Whenever I join the proxy (bound to 127.0.0.1:25568 and goes to play.purpleprison.net:25565) on MC 1.20.6, it gives me the following error:

"Internal Exception: io.netty.codec.DecoderException: Recieved unknown packet id -1"

And I do not know what this is, nor how to fix it.
I do have a dump created, it is [here](https://dump.viaversion.com/f548a157e78dc26b9b1e7566263e9bbec1175ae76e98567fc46b31e45a68ff79) if that helps.

Console log:

[15:44:07] [main/INFO] (ViaProxy) Initializing ViaProxy GUI v3.2.2 (git-ViaProxy-3.2.2:01c94f8) (Injected using Launcher Agent)...
[15:44:07] [main/INFO] (ViaProxy) Using java version: Java HotSpot(TM) 64-Bit Server VM 17.0.11 (Oracle Corporation) on Windows 10
[15:44:07] [main/INFO] (ViaProxy) Available memory (bytes): 8535408640
[15:44:07] [main/INFO] (ViaProxy) Working directory: C:\Users\*******\Desktop\vp
[15:44:07] [Via-Mappingloader-0/INFO] (ViaVersion) Loading block connection mappings ...
[15:44:08] [main/INFO] (ViaBackwards) Loading translations...
[15:44:08] [main/INFO] (ViaBackwards) Registering protocols...
[15:44:08] [main/INFO] (ViaRewind) Registering protocols...
[15:44:08] [main/INFO] (ViaBedrock) Started resource pack HTTP server on http://127.0.0.1:54930/
[15:44:08] [main/INFO] (ViaVersion) ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[15:44:08] [main/INFO] (ViaVersion) Highest supported version by the proxy: 1.20.5-1.20.6 (766)
[15:44:09] [main/INFO] (ViaProxy) ViaProxy started successfully!
[15:44:11] [Via Async Scheduler 0/INFO] (ViaVersion) Finished mapping loading, shutting down loader executor!
[15:44:58] [Thread-3/INFO] (ViaProxy) Starting proxy server
[15:44:58] [Thread-3/INFO] (ViaProxy) Binding proxy server to 0.0.0.0:25568
[15:45:22] [ForkJoinPool.commonPool-worker-2/INFO] (ViaProxy) [CONNECT] (127.0.0.1:54974 | null) [1.20.5-1.20.6 <-> 1.20.5-1.20.6] Connecting to play.purpleprison.net:25565
[15:45:22] [Netty NIO Client IO #0/INFO] (ViaProxy) [DISCONNECT] (127.0.0.1:54974 | gl1tchy1203) Connection closed
[15:45:39] [ForkJoinPool.commonPool-worker-2/INFO] (ViaProxy) [CONNECT] (127.0.0.1:54992 | null) [1.20.5-1.20.6 <-> 1.20.5-1.20.6] Connecting to play.purpleprison.net:25565
[15:45:39] [Netty NIO Client IO #1/INFO] (ViaProxy) [DISCONNECT] (127.0.0.1:54992 | gl1tchy1203) Connection closed
via dump
[15:45:48] [Via Async Task 0/INFO] (ViaVersion) We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/f548a157e78dc26b9b1e7566263e9bbec1175ae76e98567fc46b31e45a68ff79

Please help!!

**Comment by RaphiMC** [comment] 2024-05-26 19:51
Check if the error is fixed with the latest dev build: https://ci.viaversion.com/view/Platforms/job/ViaProxy/

**Comment by gl1tchy1203** [comment] 2024-05-26 20:09
> Check if the error is fixed with the latest dev build: https://ci.viaversion.com/view/Platforms/job/ViaProxy/

Sooo the version and stuff I used was on a test enviornment (Windows 10 with java 17) but my runtime enviornment is raspbian with java 21 and with that one it never says the green text that says it's running and after it kept giving me that error it just times out :c

**Comment by RaphiMC** [comment] 2024-05-26 20:10
Upload the log

**Comment by gl1tchy1203** [comment] 2024-05-26 20:17
> Upload the log

https://mclo.gs/F0NRWjf

**Comment by RaphiMC** [comment] 2024-05-26 20:22
You never connected to the proxy because you stopped it after starting it

**Comment by gl1tchy1203** [comment] 2024-05-26 20:23
> You never connected to the proxy because you stopped it after starting it

I tried but it just times out

**Comment by RaphiMC** [comment] 2024-05-26 20:31
Make sure to connect to 127.0.0.1:25565 as thats the bind address you configured. To see the green text make the GUI larger

**Comment by gl1tchy1203** [comment] 2024-05-26 20:39
> Make sure to connect to 127.0.0.1:25565 as thats the bind address you configured. To see the green text make the GUI larger

So the text appears now, meaning it's running, but even on the Pi itself on 127.0.0.1:25565 I get timed out.

**Comment by RaphiMC** [comment] 2024-05-26 20:40
Can you record a video. I am not sure how else to debug this any further as its working for me on Windows

**Comment by gl1tchy1203** [comment] 2024-05-26 20:51
https://file.io/GvaoUwGEOfVM

This link should download the recording

**Comment by RaphiMC** [comment] 2024-05-26 20:58
This almost certainly is a system misconfiguration as thats the first report of such an issue (And I just confirmed that it works for me on Windows 10). Can you check if the original error is fixed by running it in your Windows 10 environment instead of the Pi.

**Comment by gl1tchy1203** [comment] 2024-05-26 21:00
> This almost certainly is a system misconfiguration as thats the first report of such an issue (And I just confirmed that it works for me on Windows 10). Can you check if the original error is fixed by running it in your Windows 10 environment instead of the Pi.

I did try it, and on Windows 10 it does indeed work. So I guess this is something with my Pi that I can probably debug on my own.

**Comment by RaphiMC** [comment] 2024-05-26 21:01
If you found the fix for the Pi you can mention it here in case anyone else has the same issue in the future

**Closed by RaphiMC** 2024-05-26 21:01 UTC
