### ISSUE TITLE
Cant do anything when connecting to bedrock server

### ISSUE THREAD

**Issue by flori012** [ViaVersion/ViaProxy#271] opened 2024-08-10 22:46 UTC
When connecting to bedrock server with java client you cant do anything.
 - Cant fly with elytra (kicks you)
 - Cant open chests
 - Cant interact with inventory
and basically everything else that is part of minecraft

**Comment by RaphiMC** [comment] 2024-08-10 22:47
Duplicate of #267

**Closed by RaphiMC** 2024-08-10 22:47 UTC
